2025-08-13 09:47:54,446:ERROR:Error occurred in script: D:\LearnMl\Network_Security_Project\Network_security\exceptions\custom_exception.py at line number: 20 with message: This is a test error
